### ISSUE TITLE
pdf_scan.py file error

### ISSUE THREAD

**Issue by michali123** [ValeryiaPilchuk/Never_Late#44]
Hey guys, 

As I was running some tests on python.py file  I was getting the following error:
![image](https://user-images.githubusercontent.com/42022911/143731032-655aa71e-ec40-4bf2-a3e8-81834abd8257.png)

Seems like file Assignment 1 is not getting saved.
Do we care about that at all?

Let me know,
Thanks!

**Comment by alicechen1998** [comment]
I will update a new version for this code... But I think the team doesnt very use this file. You dont very need do a unit test on this file

**Comment by michali123** [comment]
ok great, thank you!

**Comment by michali123** [comment]
Re- opening in case anyone thinks we are using this python file code? 
thank you
